Repository JoinColony/JoinColony.github.io, pull requests merged in 2019-09, with the labels that each got.

#133 Temp remove ipfs dependency and functionality
  package.json
  src/modules/layouts/components/DeveloperPortalLayout/ipfs.js
  src/modules/pages/components/Contribute/Task/TaskActions/TaskActions.jsx
  src/modules/pages/components/Dashboard/Admin/AddTask/AddTask.jsx
  src/utils/ipfs/index.js
  yarn.lock
Labels: bug

#131 Fix condition for displaying MetaMask screen
  src/modules/layouts/components/DeveloperPortalLayout/DeveloperPortalLayout.jsx
Labels: bug

#121 Add a collection of beauty fixes
  src/modules/core/components/GridItem/GridItem.jsx
  src/modules/core/components/GridItem/GridItem.module.css
  src/modules/pages/components/Website/HomePage/EtherBanner/EtherBanner.jsx
  src/modules/pages/components/Website/HomePage/EtherBanner/EtherBanner.module.css
  src/modules/pages/components/Website/HomePage/Products/Products.module.css
  src/modules/pages/components/Website/HomePage/Products/SlideDevelopers/SlideDevelopers.module.css
  src/modules/pages/components/Website/HomePage/TLDR/TLDR.jsx
  static/img/screenshot_codeEditor.png
Labels: enhancement, under-review

#134 Dev Portal - Updates to dashboard admin
  .env.development.example
  .env.production.example
  .gitignore
  package.json
  src/modules/layouts/components/DeveloperPortalLayout/useColonyRoles.js
  src/modules/layouts/components/DeveloperPortalLayout/usePortalServer.js
  src/modules/pages/components/Contribute/Payment/Payment.jsx
  src/modules/pages/components/Contribute/Task/Task.jsx
  src/modules/pages/components/Contribute/Task/TaskActions/TaskActions.jsx
  src/modules/pages/components/Dashboard/Account/Address/Address.jsx
  src/modules/pages/components/Dashboard/Account/DeleteAccount/DeleteAccount.jsx
  src/modules/pages/components/Dashboard/Account/Discourse/Discourse.jsx
  src/modules/pages/components/Dashboard/Account/Email/Email.jsx
  src/modules/pages/components/Dashboard/Account/Name/Name.jsx
  src/modules/pages/components/Dashboard/Admin/Accounts/Accounts.jsx
  src/modules/pages/components/Dashboard/Admin/Accounts/Accounts.module.css
  src/modules/pages/components/Dashboard/Admin/Accounts/index.js
  src/modules/pages/components/Dashboard/Admin/AddAdmin/AddAdmin.jsx
  src/modules/pages/components/Dashboard/Admin/AddPayment/AddPayment.jsx
  src/modules/pages/components/Dashboard/Admin/AddTask/AddTask.jsx
  src/modules/pages/components/Dashboard/Admin/Admin.jsx
  src/modules/pages/components/Dashboard/Admin/Admin.module.css
  src/modules/pages/components/Dashboard/Colonies/AddColony/AddColony.jsx
  src/modules/pages/components/Dashboard/Colonies/ColonyItem/ColonyItem.jsx
  src/modules/pages/components/Dashboard/Dashboard.jsx
  src/modules/pages/components/Dashboard/Sidebar/Sidebar.jsx
  src/modules/parts/components/IssueTableRow/IssueTableRow.jsx
  yarn.lock
Labels: enhancement, under-review

#135 Add `Blog` link to footer resources menu
  src/modules/layouts/components/WebsiteLayout/Footer/Menus/Menus.jsx
Labels: enhancement

#136 Fix newsletter sign up form
  src/modules/parts/components/NewsletterCta/NewsletterCta.jsx
Labels: bug

#138 Add statically-linked Dapp T&C file
  static/pdf/terms.pdf
Labels: needs-code-review
